# Generated by Django 4.2.7 on 2023-12-03 16:38

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dueDate',
            field=models.DateField(blank=True, null=True, validators=[todo.models.Todo.no_future]),
        ),
    ]
