name: Integration

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install Dependencies
        run: |
          pip install -m requirement.txt

      - name: Run Unit Test
        run: |
          python manage.py test todobackend.unit