name: Integration

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Test
        run: |
          cd ToDoBackend-Django/todobackend/
          python manage.py test todo.tests
        working-directory: ToDoBackend-Django/todobackend/

      - name: Run Integration Tests
        run: |
          python manage.py test todo.testIntegration

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install linting tools
        run: |
          pip install flake8 black  

      - name: Run Flake8 with exclusion
        run: |
          flake8 --exclude=./todobackend/todo/migrations/*,./todobackend/todobackend/settings.py, .

      - name: Run Black
        run: |
          black --check --exclude ./todobackend/todo/migrations/* --exclude 
          ./todobackend/todobackend/settings.py --exclude ./todobackend/todobackend/wsgi.py.